spring:
  application:
    name: url-shortener
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: url_shortener
    redis:
      url: ${REDIS_URL}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email

server:
  forward-headers-strategy: framework
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

app:
  secure-code:
    secret-key: ${SECURE_CODE_SECRET_KEY}
    alphabet: ${SECURE_CODE_ALPHABET}
